// mockups/brutalist-demo/components/Typewriter.tsx
import React, { useState, useEffect, useRef } from 'react';

interface TypewriterProps {
  text: string;
  speed?: number;
  onComplete?: () => void;
  onStart?: () => void;
  className?: string;
}

export const Typewriter: React.FC<TypewriterProps> = ({ text, speed = 20, onComplete, onStart, className }) => {
  const [displayedText, setDisplayedText] = useState('');
  const indexRef = useRef(0);
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null);

  // Reset when text changes
  useEffect(() => {
    setDisplayedText('');
    indexRef.current = 0;
    
    if (onStart) onStart();
    if (timerRef.current) clearInterval(timerRef.current);

    timerRef.current = setInterval(() => {
      if (indexRef.current < text.length) {
        setDisplayedText((prev) => prev + text.charAt(indexRef.current));
        indexRef.current++;
      } else {
        if (timerRef.current) clearInterval(timerRef.current);
        if (onComplete) onComplete();
      }
    }, speed);

    return () => {
      if (timerRef.current) clearInterval(timerRef.current);
    };
  }, [text, speed, onComplete, onStart]);

  return (
    <span className={className}>
      {displayedText}
      <span className="inline-block w-2 h-4 ml-1 align-middle bg-current animate-cursor"></span>
    </span>
  );
};

// packages/app-svelte/src/lib/components/Typewriter.svelte
<script lang="ts">
	import { onMount, onDestroy, untrack } from 'svelte';

	/**
	 * Task 015: Typewriter Component
	 *
	 * Reveals text character-by-character with configurable speed
	 * and callbacks for syncing with KOA avatar state.
	 */

	interface Props {
		/** Text to reveal character by character */
		text: string;
		/** Milliseconds per character (default: 20) */
		speed?: number;
		/** Called when typing starts */
		onStart?: () => void;
		/** Called when typing finishes */
		onComplete?: () => void;
	}

	let { text, speed = 20, onStart, onComplete }: Props = $props();

	let displayedText = $state('');
	let interval: ReturnType<typeof setInterval> | null = null;
	let previousText = $state<string | undefined>(undefined);

	function stopTyping() {
		if (interval) {
			clearInterval(interval);
			interval = null;
		}
	}

	function startTyping(textToType: string) {
		stopTyping();
		displayedText = '';

		onStart?.();

		// Handle empty text case
		if (textToType.length === 0) {
			onComplete?.();
			return;
		}

		let idx = 0;
		interval = setInterval(() => {
			if (idx < textToType.length) {
				idx++;
				displayedText = textToType.slice(0, idx);
			}
			if (idx >= textToType.length) {
				stopTyping();
				onComplete?.();
			}
		}, speed);
	}

	onMount(() => {
		previousText = text;
		startTyping(text);
	});

	onDestroy(() => {
		stopTyping();
	});

	// Handle text changes - restart typing with new text
	$effect(() => {
		// Access text to create dependency
		const currentText = text;
		// Only restart if text actually changed (not on initial mount)
		const prev = untrack(() => previousText);
		if (prev !== undefined && currentText !== prev) {
			previousText = currentText;
			startTyping(currentText);
		}
	});
</script>

<span>{displayedText}<span class="inline-block w-2 h-4 ml-1 align-middle bg-current animate-cursor"></span></span>
